Vagrant.configure("2") do |config|

	# Server configuration
	config.vm.define "alouziziS", primary: true do |server|
	  server.vm.box = "debian/bullseye64"
	  server.vm.hostname = "alouziziS"
	  server.vm.network "private_network", ip: "192.168.56.110"
	  server.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
	  end
	  server.vm.provision "file", source: '~/.ssh/id_rsa.pub' , destination: "~/.ssh/me.pub"

	  server.vm.provision "shell", path: "scripts/server_setup.sh"
	end

	# Worker configuration
	config.vm.define "adaifiSW" do |worker|
	  worker.vm.box = "debian/bullseye64"
	  worker.vm.hostname = "adaifiSW"
	  worker.vm.network "private_network", ip: "192.168.56.111"
	  worker.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
	  end
	  worker.vm.provision "file", source: '~/.ssh/id_rsa.pub' , destination: "~/.ssh/me.pub"
	  worker.vm.provision "shell", path: "scripts/worker_setup.sh"
	end
  end